### ISSUE TITLE
For the sake of traceability

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/hl7.be.fhir.template#18]
@costateixeira 
@jmp-ehealth 

I could not find an issue linked to this commit: https://github.com/hl7-be/hl7.be.fhir.template/commit/71817635d08477a1b90d64563ca9726b8e1120d7

Could you please provide one for the sake of traceability?

**Comment by costateixeira** [comment]
Sure. This was a rather urgent change to make sure nothing would break. 
#19.
